### ISSUE TITLE
Decoding: Configuration.default.withDefaults makes it use the default value when the decoding the field failed

### ISSUE THREAD

**Issue by laszlox** [circe/circe#1024]
I'm using the Configuration.default.withDefaults feature and lots of my case classes have defaults values for members. However, when decoding a json where there is an error (e.g. type mismatch) it uses the default value and swallows the error:

```scala
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.auto._

implicit val customConfig: Configuration = Configuration.default.withDefaults
final case class Foo(number: Int = 999)
io.circe.parser.decode[Foo]("""{"number": "not a number!"}""")

res0: Either[io.circe.Error,Foo] = Right(Foo(999))
```

Ideally, I'd like the default value to be used only if the field was missing from the json, and get an error when it was there but incorrectly.

Can I change this behavior somewhere central so that I don't need to have custom decoders for all my case classes with defaults?

**Comment by exoego** [comment]
Maybe this PR ?https://github.com/circe/circe/pull/994

**Comment by laszlox** [comment]
I think that doesn't fix it, because it changes the decode behavior only for options, but even for options this PR makes decoding fall back to the default in more cases (missing key), still including type-mismatch or other errors.

Seems like the Decoder.Result should really represent 3 different things: success (right), error (left), missing (?) and the orDefault could fall back to default only in case of "missing", errors would be propagated.

**Comment by travisbrown** [comment]
I agree that this is a bug. Unfortunately it's not trivial to fix, since the default decoding works with results, not cursors, which would make things a lot simpler.

I'm not personally using circe-generic-extras at the moment, and can't really prioritize fixing this, but contributions are very welcome.

**Comment by froth** [comment]
@travisbrown I drafted something:
https://github.com/circe/circe/compare/master...froth:fixWithDefault

Instead of giving the Result to orDefault passing cursor and codec.
This of course changes the interface of ReprDecoder. I believe this is in inevitable. Would that be ok?

If you are ok with my idea of fixing the issue I would invest some time and pull it through for orDefault and orDefaultAccumulating.

**Comment by froth** [comment]
Bonus Question: 
orDefault and orDefaultAccumulating are basically the same code. I think it would be possible to abstract over ApplicativeError. I am not sure if this would be overkill and/or would affect the performance. what do you think?

**Comment by froth** [comment]
Took the time to try the ApplicativeError idea it out and found it was more complicated than helpful. But finished the pull request anyway while doing so. ;) Please have a look.
