### ISSUE TITLE
How to ignore Json capitalization in the Circe

### ISSUE THREAD

**Issue by yuer2016** [circe/circe#1038]
When json decodes, the case of the field will affect whether the decoding is successful. How to ignore this .  example:  {name:"tom"}  {"NAME":"tom"}

**Comment by travisbrown** [comment]
Sorry for missing this issue, but it would be probably be better as a Stack Overflow question since it doesn't propose a change or report a bug.

The solution will depend on what kinds of variation are possible. One approach would be to accept both:

```scala
scala> import io.circe.Decoder, io.circe.literal._
import io.circe.Decoder
import io.circe.literal._

scala> case class Person(name: String)
defined class Person

scala> implicit val decodePerson: Decoder[Person] = {
     |   val d = Decoder[String].map(Person(_))
     |   d.prepare(_.downField("name")) or d.prepare(_.downField("NAME"))
     | }
decodePerson: io.circe.Decoder[Person] = io.circe.Decoder$$anon$9@18ecf886

scala> json"""{"NAME":"tom"}""".as[Person]
res0: io.circe.Decoder.Result[Person] = Right(Person(tom))

scala> json"""{"name":"tom"}""".as[Person]
res1: io.circe.Decoder.Result[Person] = Right(Person(tom))
```
Another would be to transform all incoming JSON so that keys are lower-cased, etc.

**Comment by satyagraha** [comment]
I was trying something similar to uncapitalize JSON using Optics as shown in https://gist.github.com/satyagraha/cbb818b2edd27ebe38d72bfd0f58ee11
However, the top-level JSON object does not get transformed, but the lower-level ones do - any ideas?
