### ISSUE TITLE
Issue with unused `io.circe.generic.auto._`

### ISSUE THREAD

**Issue by leobenkel** [circe/circe#1043]
Hello,

In my code I have  `import io.circe.generic.auto._` in the root of my file, and inside my `case class` I have 

```
implicit private val jsonEncoder: Encoder[MyCaseClass]
```

But ScalaFix is telling me that I do not need the import, which should make sense since I add my own encoder. However, if I remove the `import`, I then get IntelliJ having issues about : 
```
No implicits found for parameter encoder: Encoder[MyCaseClass.this.type]
```

So I tried to give it the encoder manually:

```
this.asJson(jsonEncoder)
```

But I then get: 

```
Type mismatch, expected: Encoder[MyCaseClass.this.type], actual: Encoder[MyCaseClass]
```

Any idea what is going on  ?

**Comment by travisbrown** [comment]
Without a more complete example it's hard to say what exactly the problem is, but there are lots of things that sound like red flags:

- Why is the `Encoder` instance private?
- Why is it in the companion object?
- Why are you defining an instance at all if you're using `auto`?
- Are you sure the `this` isn't referring to the companion object?

Feel free to re-open this issue with a minimal complete example, but as it is I'm not sure I can help.
