### ISSUE TITLE
Auto derivation fails for base trait with no generic parameter

### ISSUE THREAD

**Issue by kamilkloch** [circe/circe#1103]
This compiles:
```scala
  import io.circe.syntax._
  import io.circe.generic.auto._  
  
  sealed trait A[T]
  case class B[T](b: T) extends A[T]

  val b = B(1.0)
  println(b.asJson.noSpaces)
  val a: A[Double] = b
  println(a.asJson.noSpaces)
```

This fails:
```scala
  import io.circe.syntax._
  import io.circe.generic.auto._

  sealed trait A
  case class B[T](b: T) extends A

  val b = B(1.0)
  println(b.asJson.noSpaces)
  val a: A = b
  println(a.asJson.noSpaces) // does not compile
```

Why?

**Comment by travisbrown** [comment]
The issue is that you need to know at compile-time that all of the members of the case class can be encoded, so the following must not compile:

```scala
trait Nonsense
val a: A = B(new Nonsense {})
val encoded = a.asJson
```

But that `A` is exactly the same as the `A` in your second example.

It's worth noting that Shapeless doesn't provide a `LabelledGeneric` (or `Generic`) instance for your second `A`, either. Also, to be honest I'm a little surprised that your first example works (and in fact it doesn't seem to on 2.11). It's clearly fine, but I wouldn't expect the compiler / these macros to be able to figure that out.
