### ISSUE TITLE
Stable scala 2.13 release?

### ISSUE THREAD

**Issue by erikvanoosten** [circe/circe#1195]
Is it possible to publish a stable release for Scala 2.13?
For example, Circe 0.11.1 could be released for Scala 2.13.

**Comment by travisbrown** [comment]
This isn't possible yet because there's no stable Cats release for 2.13. There's no stable Cats release for 2.13 because there's no stable ScalaTest release for 2.13 that's compatible with ScalaCheck 1.14, and Cats publishes one module from its core repository that depends on ScalaTest. It's a bad situation all around, but it seems like it will be resolved within the next few weeks, and my plan is to have a new circe release within a day or two of Cats 2.0.0.

**Comment by travisbrown** [comment]
I'm going to close these issues that are blocked by dependencies (since they aren't actionable and have less value as reminders now that Scala Steward keeps us updated).

**Comment by erikvanoosten** [comment]
Tip: github allows you to subscribe to release notifications only.
