### ISSUE TITLE
JsonCodec, encoder for polymorphic type not found (circe 0.12.3)

### ISSUE THREAD

**Issue by dcastro** [circe/circe#1388]
# Demo

```scala
@JsonCodec
case class Test[A](value: A)

object Test {
  val a =  Encoder[Test[Int]]

  def func[A: Encoder]: Unit = {
    val b = Encoder[Test[Int]]
    val c = Encoder[Test[A]]
    ???
  }
}
```

# Expected result
I expected all 3 calls to `Encoder.apply` to find the right implicit encoder and compile.

# Actual result
This code compiled just fine with circe 0.11.1, but it stopped compiling after I upgraded to 0.12.3.

The implicits for `val a` and `val b` are successfully found (by composing the encoder generated by the macro with `Encocer.encodeInt`), but the implicit for `val c` is not found.

```scala
Error:(65, 12) could not find implicit value for parameter instance: io.circe.Encoder[tv.spotx.lady.kafka.Test[A]]
    Encoder[Test[A]]
```

**Comment by travisbrown** [comment]
Hmm, this is because `JsonCodec` uses the new `io.circe.Codec` helper that was introduced in 0.12.3, because this can reduce compile times, etc. The problem is that this means that in order to get an `Encoder` for a generic case class, you need both an encoder and a decoder for the element type(s).

There are a several workarounds. One is to add a `Decoder` constraint to `func`. Another would be to use `@JsonCodec(encodeOnly = true)` (if you only need an encoder). You could also switch explicit semi-automatic derivation with `deriveDecoder` and `deriveEncoder`.

If someone wanted to open a PR changing the `@JsonCodec` macro back to using `deriveEncoder` and `deriveDecoder` instead of `deriveCodec`, and to confirm that it's bincompat, I'd happily review, but I don't think I'll have time to do this myself before 0.13.0.

**Comment by travisbrown** [comment]
On second thought I'll go ahead and change this back in 0.13.0, assuming it doesn't break bincompat, which it shouldn't (but it won't be backported to 0.12, since I don't want to change the behavior mid-release series).

**Comment by dcastro** [comment]
Thank makes sense, thank you for the explanation :)
