### ISSUE TITLE
deriveConfiguredEncoder unexpected behaviour with value classes

### ISSUE THREAD

**Issue by ikempf** [circe/circe#1461]
I have been using `generic.semiauto` and `generic.extras.semiauto` quite a bit but there are cases when I cannot manage to get the desired output.

When using value/wrapper classes inside an adt it seems that `deriveConfiguredEncoder` behaves the same as `deriveEncoder`.

Take the following ADT and encoders:
```scala
sealed trait Parent
case class ValueClass(value: ClassA) extends Parent
case class ClassA(a: String, b: String)

implicit val conf: Configuration           = Configuration.default.withDiscriminator("type")
implicit val encoderA: Encoder[ClassA]     = deriveEncoder
implicit val encoderV: Encoder[ValueClass] = Encoder[ClassA].contramap(_.value)
implicit val encoder: Encoder[Parent]      = deriveConfiguredEncoder
```
Given these encoders, serializing `ValueClass` results in the following json:
```scala
Encoder[Parent].apply(ValueClass(ClassA("a", "b")))
```
```json
{
  "ValueClass": {
    "a": "a",
    "b": "b"
  }
}
```
But given the `Configuration` I expected this json:
```json
{
  "a": "a",
  "b": "b",
  "type": "ValueClass"
}
```

Is there a way to achieve the desired output ? Is this behaviour expected from `deriveConfiguredEncoder` ?

**Comment by travisbrown** [comment]
The problem here is that `encoderV` isn't guaranteed to encode its inputs as JSON objects, so circe-generic-extras doesn't know that it can use the `"type": "..."` encoding, and has to fall back to the default object wrapper encoding.

Imagine for example that you had the following:
```scala
// ...
case class ValueClass(value: String) extends Parent
// ...
implicit val encoderV: Encoder[ValueClass] = Encoder[String].contramap(_.value)
// ...
```
Now if you call `Encoder[Parent].apply(ValueClass("foo"))`, the JSON encoding of `ValueClass("foo")` would just be `"foo"`, which the derived encoder can't add a `type` field to.

The solution is to use `Encoder.AsObject` and `contramapObject` to maintain the information that the encoding of `ValueClass` will always give a JSON object:

```scala
import io.circe.Encoder
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.semiauto.deriveConfiguredEncoder
import io.circe.generic.semiauto.deriveEncoder

sealed trait Parent
case class ValueClass(value: ClassA) extends Parent
case class ClassA(a: String, b: String)

implicit val conf: Configuration = Configuration.default.withDiscriminator("type")

implicit val encoderA: Encoder.AsObject[ClassA] = deriveEncoder
implicit val encoderV: Encoder.AsObject[ValueClass] =
  Encoder.AsObject[ClassA].contramapObject(_.value)

implicit val encoder: Encoder[Parent] = deriveConfiguredEncoder
```
This works as expected:
```scala
scala> Encoder[Parent].apply(ValueClass(ClassA("a", "b")))
val res0: io.circe.Json =
{
  "a" : "a",
  "b" : "b",
  "type" : "ValueClass"
}
```
Please feel free to re-open if that doesn't resolve the issue for you!

**Comment by travisbrown** [comment]
As a side note, there's an argument that we should have ADT instance derivation fail in cases where you've configured `withDiscriminator` and have an `Encoder` for one of the constructors that isn't an `Encoder.AsObject`, instead of falling back to the default behavior.

I think I personally prefer the current fallback behavior, but don't have a strong opinion either way. If someone wants to propose this as a PR against the circe-generic-extras repository, I'm happy to discuss it in more detail.

**Comment by ikempf** [comment]
`Encoder.AsObject`, that makes total sense, solved my issue. Thanks 👍
