### ISSUE TITLE
Automatic derivation used despite implicit decoder in scope

### ISSUE THREAD

**Issue by oscar-broman** [circe/circe#1466]
```scala
import scala.util.Try

import io.circe.Decoder._
import io.circe.generic.auto._
import io.circe.{Decoder, Encoder}

case class MyClass()

object MyClass {
  implicit def myEncoder: Encoder[MyClass] = ???
  implicit def myDecoder: Decoder[MyClass] = ???
}

object Test {
  def encoder = implicitly[Encoder[MyClass]]
  def decoder = implicitly[Decoder[MyClass]]

  def main(args: Array[String]): Unit = {
    println(s"encoder = ${Try(encoder)}")
    println(s"decoder = ${Try(decoder)}")
  }
}
```

Output:
```
encoder = Failure(scala.NotImplementedError: an implementation is missing)
decoder = Success(io.circe.generic.decoding.DerivedDecoder$$anon$1@63420df2)
```

**Comment by oscar-broman** [comment]
I realize now that removing the `io.circe.Decoder._` import solves the problem.

Why does the priority change from that import?

**Comment by travisbrown** [comment]
The issue is that when you import `Decoder._`, you raise this low-priority decoder from implicit scope into actual scope scope:

```scala
implicit def importedDecoder[A](implicit exported: Exported[Decoder[A]]): Decoder[A] = exported.instance
```

The `Exported[Decoder[A]]` is provided by a macro in `generic.auto` in such a way that it won't override user-defined instances. That prioritization depends on `importedDecoder` only being in implicit scope, though. Once you import it, the priorities go out the window, and it takes precedence over user-defined instances in implicit scope.

The solution is not to import `Decoder._`.
