### ISSUE TITLE
Build and publish for recent dotty milestones

### ISSUE THREAD

**Issue by LukaJCB** [circe/circe#1572]
cats-core and scalacheck have been published for the latest 3.0.0-M1 release. It'd be great if we could get a circe release targeting the same version too.

**Comment by travisbrown** [comment]
I think this is still blocked on at least discipline-scalatest (I wish Circe were already migrated over to MUnit but I don't know when that will happen). I don't have much time for these projects these days but am happy to take a closer look once all dependencies are ready.

**Comment by larsrh** [comment]
I just released 2.1.0 for Dotty 3.0.0-M1.

**Comment by travisbrown** [comment]
I've tagged this as LSUG for the hackathon today, and I'll probably work on this repo in the absence of other things to do, but we also need to add Dotty / Scala 3 to the builds for the [other repos in the Circe org](https://github.com/circe) (most of which shouldn't be blocked by Circe itself, because they don't depend on e.g. circe-generic), if anyone is looking for more intermediate-to-advanced level tasks.

**Comment by travisbrown** [comment]
Closing this since most Circe modules are now published for 3.0.0-RC1 (3.0.0-M3 support was introduced in December): https://github.com/circe/circe/releases/tag/v0.14.0-M4
