### ISSUE TITLE
Is it possible to have an Encoder with the shape  Encoder[Seq[Something]]?

### ISSUE THREAD

**Issue by SarpongAbasimi** [circe/circe#1621]
Please how can I go from `Encoder[Seq[Something]]` to `json`

```
    implicit val encoderForListMovie = new Encoder[Seq[Movie]] {
      final def apply(a: Seq[Movie]): Json = {
        ???
      }
    }
```

The only thing that comes to mind to go from `Seq[Something]` to `Something` is `fold` and `reduce` but that is not what I want. If you could help, I will be very grateful thank you

**Comment by travisbrown** [comment]
Circe automatically provides `Encoder` and `Decoder` instances for many types in the standard library, including `Seq`. For generic types like `Seq`, these are _derived_ instances, where for example if you have an encoder for a type `Foo`, Circe automatically provides an encoder for `Seq[Foo]`.

For example, suppose you have this code:

```scala
import io.circe.Encoder

case class Movie(title: String)

object Movie {
  // Details aren't relevant, just the fact that we have an instance.
  implicit val encodeMovie: Encoder[Movie] = Encoder[String].contramap(_.title)
}
```

Then you automatically get an implicit `Encoder[Seq[Movie]]` anywhere you need it:

```scala
scala> Encoder[Seq[Movie]]
val res0: io.circe.Encoder[Seq[Movie]] = io.circe.Encoder$$anon$23@5d39c9d3

scala> Encoder[Seq[Movie]].apply(List(Movie("Foo"), Movie("Bar")))
val res1: io.circe.Json =
[
  "Foo",
  "Bar"
]
```

Ideally you should never define your own implicit `Encoder[Seq[Something]]`, because that would mean one of two things:

1. Your custom instance has the same behavior as the default derived `Seq` instance, in which case it is unnecessary.
2. Your custom instance has different behavior from the default derived `Seq` instance, in which case it's likely to confuse users, or yourself at some point in the future.

There are some rare cases where it may be reasonable to define a non-implicit `Seq` instance (for example if you don't have an implicit instance for the element type for some reason), which you can do with `Encoder.encodeSeq`:

```scala
scala> val enc = Encoder.encodeSeq(Movie.encodeMovie)
val enc: io.circe.Encoder.AsArray[Seq[Movie]] = io.circe.Encoder$$anon$23@53717af0

scala> enc(List(Movie("Foo"), Movie("Bar")))
val res4: io.circe.Json =
[
  "Foo",
  "Bar"
]
```

In general that shouldn't be necessary, though.

Please feel free to reopen this issue if any of this isn't clear.

**Comment by SarpongAbasimi** [comment]
@travisbrown thank you very much. The issue have been resolved now.
Please may I ask if you could explain what `contramap` does and where this can be used.

**Comment by travisbrown** [comment]
You can think of `contramap` as attaching a transformation before another transformation in a pipeline. An `Encoder[B]` is essentially a `B => Json`, and if you have `encodeB: Encoder[B]` and a function `a2b: A => B`, you can use contramap to chain the `A => B` and `B => Json` to get an `Encoder[A]` with `encodeB.contramap(a2b)`.
