### ISSUE TITLE
val in case class body not encoded

### ISSUE THREAD

**Issue by cjaber** [circe/circe#1697]
Hello
When using generic or semi automatic derivation to encode a case class with a val in the body like in the following example:
```
case class Foo(id: String, nb:Int ) {
  val bar: String = "Foo"
}
``` 
I expect to have a json object with a bar field but this is not the case.
Maybe this is related to the https://github.com/circe/circe/issues/1406

**Comment by travisbrown** [comment]
This is out of scope for circe-generic, since it follows the generic encoding used by Shapeless, which does not include `val`s in case classes:

```scala
scala> case class Foo(id: String, nb:Int ) {
     |   val bar: String = "Foo"
     | }
class Foo

scala> shapeless.LabelledGeneric[Foo]
val res0: shapeless.LabelledGeneric[Foo]{type Repr = String with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("id")],String] :: Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("nb")],Int] :: shapeless.HNil} = shapeless.LabelledGeneric$$anon$1@31edae57
```

In general circe-generic follows Shapeless, which in this case means that it compiles even if the case class has `val`, but silently ignores them.

This functionality wouldn't necessarily be out of place in circe-generic-extras or circe-derivation. Personally I think Shapeless makes the right choice here, and find `val`s in case classes unidiomatic, but I'd be happy to review PRs if there's sufficient interest and someone else wants to do the work.
