### ISSUE TITLE
Publish for 3.0.0-RC2

### ISSUE THREAD

**Issue by aeons** [circe/circe#1712]
Are there any dependencies blocking a publish of 0.14.0-M4 for 3.0.0-RC2?

**Comment by travisbrown** [comment]
I don't think so. I can plan to publish a release for 3.0.0-RC2 this evening (although it'll need to be M5, since there are some necessary patch version bumps since M4, and I want to avoid differing dependency versions across Scala version artifacts).

**Comment by aeons** [comment]
Sounds good to me.

**Comment by SethTisue** [comment]
https://twitter.com/travisbrown/status/1379493859785388033

**Comment by aeons** [comment]
Yep, thanks!

**Comment by nightscape** [comment]
@travisbrown it seems that `circe-generic` was cross-published to Scala 3.0.0-M3 for ScalaJS at version 0.14.0-M3, but it doesn't seem to be for 3.0.0-RC2 at version 0.14.0-M5.
https://search.maven.org/search?q=g:io.circe%20AND%20a:circe-generic_sjs1_*
Is this an oversight, or did something break in between that needs fixing before it can be published?
I'm asking because I'm trying to make `sttp-circe` work on ScalaJS for Scala 3.0.0-RC2.
Thank you!

**Comment by travisbrown** [comment]
@nightscape This wasn't an oversight, there were just failures building or publishing several of the Scala.js modules for Scala 3, and I hadn't had time to investigate them. It looks like the circe-generic issue was fairly simple and should be resolved by #1720.

**Comment by nightscape** [comment]
@travisbrown ah, great! Then I'll wait for `0.14.0-M6` and continue my `sttp-circe` efforts then 👍

**Comment by travisbrown** [comment]
@nightscape I could publish an 0.14.0-M5 circe-generic_sjs specifically today. I wouldn't publish omitted modules separately like that for a proper release, but for a milestone I don't see a problem with it, since the change was only for a test dependency.

**Comment by nightscape** [comment]
That would be perfect! Thanks a lot!

**Comment by travisbrown** [comment]
@nightscape Okay, it's on its way to Maven Central. We exclude test dependencies from the POMs, so there shouldn't be any discrepancies from the JVM circe-generic 0.14.0-M5 even in the metadata.
