### ISSUE TITLE
Allow alternate implementation of  `derives` syntax on scala 3

### ISSUE THREAD

**Issue by andimiller** [circe/circe#1717]
Currently in the scala 3 builds, there is a `Decoder.derived[A]` on the companion object in core, while there aren't equivalents on `Encoder` or `Codec`.

Since people tend to have different opinions about how derivation should be configured, it would be good if `Decoder.derived[A]` were moved to allow different derivation frameworks to extend that method onto the companion object themselves.

I've tested this by writing my own addition to `semiauto` with extensions like this:

```scala
extension (e: io.circe.Encoder$)
  inline final def derived[A](using inline A: Mirror.Of[A]) = io.circe.generic.semiauto.deriveEncoder
```

and it seems to work fine for enabling the syntax on `Encoder`/`Codec`.

I think it would be nice to follow this model to allow for `generic-extras` style configured derivation, or alternate derivation implementations.

**Comment by travisbrown** [comment]
You've confirmed that `derived` as an imported extension method supports the `derives` syntax in ADT definitions? If so I don't necessarily see a problem with requiring an import for `derives`.

(It's probably a bug that there aren't `derived` methods on `Encoder` or `Codec`, though. Maybe it's because they're on `Encoder.AsObject`, etc.? I haven't looked at this stuff in ages and don't remember.)

**Comment by heksesang** [comment]
I have confirmed that extension methods can be used to enable the `derives` syntax (it's actually really useful for enabling `derives` syntax in cross-compiled projects).

This way we could avoid `given`-based configuration of the derivation – instead of looking for some `given`, circe should provide a method that allows you to create a configured method for derivation and then you can extend `Decoder`/`Encoder`/`Codec` with that (removing the need for any `generic-extras` kind of module). At least to me that sounds like the better approach to how to implement configurable derivation.

**Comment by felixbr** [comment]
I just tested that `derives Encoder.AsObject` does indeed work. A bit confusing but still awesome 🙌

Example: https://scastie.scala-lang.org/DOFqYNQATtOBADYQriVwIg
