### ISSUE TITLE
Publish `versionScheme`

### ISSUE THREAD

**Issue by majk-p** [circe/circe#1787]
In 1.5.0 sbt has [introduced eviction errors](https://scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html). It would be nice if circe could publish `versionScheme` to fail builds when incompatible circe versions are present in dependencies.

Can we set `versionScheme` to `early-semver` for circe?

I'd be glad to make a PR if needed.

**Comment by adamnfish** [comment]
This would be great, but for it to work circe would need to move to a `1.x` release. Version schemes typically treat `0.x` versions as "development", so the standard rules of compatibility will not apply.

Here's the reference in the sbt documentation that describes the supported options, in all these cases the current circe approach will not work:
https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme

I certainly agree with the goal of this issue though! The ecosystem now supports a mechanism for eliminating spurious eviction errors on compatible circe versions, which would be very helpful.

**Comment by majk-p** [comment]
Thanks for the input Adam! Can you please tell a little more about current circe approach to versionning? Is it possible that patch updates could break binary compatibility?

**Comment by adamnfish** [comment]
Version 0.14.x of circe is backwards-binary-compatible with 0.13.x versions, as you'd expect for a minor change in a mature library, but as you might not expect for a pre-release minor bump. The assumption that this works informs decisions like the choice [not to specifically publish libraries to maintain version parity](https://github.com/circe/circe-derivation/issues/346#issuecomment-910219725).

At the moment, this backwards-compatibility is only by "word-of-mouth". People need to have engaged with the community to know that this backwards-compatibility is an option at these pre-release / in-development versions. As far as I can tell, this compatibility isn't mentioned in the README or the guide, so I think we've all just accepted this through osmosis from somewhere 😅.

As I understand it, circe does currently commit to ensuring compatibility between patch updates, but minor version updates may or may not maintain compatibility.

Support for version schemes in sbt provides a way for us to not just document version compatibility, but have that behaviour meaningfully affect the developer experience through our use of tools. However, this will only ever be as good as our use of version numbers! At the moment, circe does not conform to any common versioning standard. Ad-hoc backwards compatibility between (some of the) minor versions is practically depended on by us all, but not documented or enforced. To resolve this for circe at the moment there are two options:

1) change sbt - add a new versioning scheme to sbt that matches how circe behaves
2) change circe - have circe adopt "early-semver" (or some other supported versioning standard)

The former is a tricky choice, because circe's backwards compatibility is ad-hoc. 0.14.x has backwards compatibility with 0.13.x, but probably not 0.1.x! This means that I suspect the only realistic choice is for circe to release a 1.x branch alongside a commitment to stick to a supported version scheme in the future.

Unfortunately I think this is a blocker to circe adopting a versionScheme. With circe being at the heart of so much of the Scala ecosystem, I think it's a great example of a library where versionSchema would bring a huge benefit!

**Comment by majk-p** [comment]
I agree it would be great to have circe adopt `versionScheme`. For the time being, I'm wondering if `semver-spec` isn't something that correctly describes present behavior, quoting the [sbt versionSchem docs](https://www.scala-sbt.org/1.x/docs/Publishing.html#Version+scheme)

> Some("semver-spec") | Semantic Versioning where all 0.y.z are treated as initial development (no bincompat guarantees)

Do you think starting with `semver-spec` and then aiming to adopt `early-semver` makes sense? I guess this would at least set the right level of expectations for the start :wink: 

On the other hand, perhaps this is a good place to start adopting. In my understanding going for `early-semver` doesn't mean that `0.X.0` is compatible with `0.{X+1}.0` but it's only about every patch within `0.X.Y` is backward compatible. In my understanding it exactly matches the way you describe the current state anyway:

> As I understand it, circe does currently commit to ensuring compatibility between patch updates, but minor version updates may or may not maintain compatibility.

**Comment by adamnfish** [comment]
The trouble is that right now the ecosystem [depends](https://github.com/circe/circe-derivation/issues/346#issuecomment-910219725) on compatibility between `0.13.x` and `0.14.x` but adding a `versionScheme` would explicitly instruct tools to consider these as incompatible. As far as I can see, none of the supported version schemes would treat these two versions as compatible so we'd be needing circe to move to a new version anyway. If that's happening, then it ought really switch to `1.x` so that in the future these backwards-compatible changes can be properly conveyed by the chosen scheme.

In the absence of a version scheme the current ambiguity is "ok but annoying" (as ok as any JVM eviction!), but adopting a version scheme should always come with a commitment to stick properly to that scheme in future.

**Comment by armanbilge** [comment]
@majk-p @adamnfish thanks for discussing this important topic, I only skimmed your conversation, but here are a couple pointers that might be helpful.

1. Circe publishes its version scheme. `<info.versionScheme>early-semver</info.versionScheme>`
https://repo1.maven.org/maven2/io/circe/circe-core_2.13/0.14.3/circe-core_2.13-0.14.3.pom

2. It follows the versioning rules described here:
https://typelevel.org/sbt-typelevel/faq.html#what-is-a-base-version-anyway

Let me know if you have any questions :)

**Comment by majk-p** [comment]
Then I think it makes this issue basically solved :wink:

**Comment by adamnfish** [comment]
I agree it sounds like this issue is already addressed, thank you!

Thank you for sharing those links, @armanbilge. Looking back at previous pom files it seems the `versionScheme` setting was included in circe's most recent release, `0.14.3`.

This means my fears may have already come true, and I suspect that is why the bump to `0.14.3` breaks the build on projects that transitively include circe at version `0.13.x`. According to the "base version" FAQ rules you have linked to, the version change from `0.13.x` to `0.14.x` should indicate a binary breaking change for circe, and sbt will now enforce this rule for us all. As you know, this is not the case! Circe's minor version changes sometimes provide binary compatibility and when they do, the community relies on it.

Now that circe is declaring it obeys `early-semver` rules by including a `versionScheme`, any project that depends directly or indirectly on circe at both `0.13.x` and `0.14.3` will now have incorrect binary incompatibility errors. Circe's own `circe/circe-derivation` has not been published for `0.14.x`, so even within the core circe experience we'll expect developers to be seeing broken builds after bumping a patch version.

If circe's goal is to avoid relying on binary compatibility between minor releases then the community will have some work to do now to make sure we are fully dropping `0.13.x`, but we'll know in the future not to rely on previous versions. If binary compatibility between versions remains a goal, then it will be much easier to manage this "semantically" from a `1._._` release that allows compatible API changes to be represented as minor changes separately from breaking changes, represented as major version bumps.

As above, I'm delighted to see that versionScheme has been rolled out. Thank you to the team for getting to it.

**Comment by armanbilge** [comment]
> According to the "base version" FAQ rules you have linked to, the version change from 0.13.x to 0.14.x should indicate a binary breaking change for circe, and sbt will now enforce this rule for us all. As you know, this is not the case!

I am not sure what you mean by "this is not the case". In case there is any doubt, the release notes for Circe 0.14.0 clearly indicate that it is mostly but not 100% binary-compatible with 0.13.x.

> This release is mostly binary-compatible with 0.13.x, which in turn was mostly binary-compatible with 0.12.x. 

https://github.com/circe/circe/releases/tag/v0.14.0

Hence, the version bump is appropriate.

**Comment by adamnfish** [comment]
I've been referring to [this comment on circe-derivation](https://github.com/circe/circe-derivation/issues/346#issuecomment-910219725) that states circe core is binary compatible across those versions. This compatibility was the reason for not needing to publish versions in sync with the rest of the circe ecosystem. In any case, it sounds like circe-derivation will get a new release soon.

I am concerned that communicating this approach to compatibility through the way the core packages are maintained means the sudden introduction of a new binary compatibility constraint in a patch-release is going to cause more problems for the community.

No harm though, once again it's fantastic to see the versionScheme being used here.

**Comment by armanbilge** [comment]
I see, thanks for that pointer. I was not aware that users were expected to rely on that. Although that may have been true that core 0.14.0 was binary-compatible with core 0.13.x, this relationship is not currently enforced in CI so it is not something you should count on.

Note that just because 0.14.x is binary-compatible with 0.14.0, and 0.14.0 is binary-compatible with 0.13.x, does not mean that 0.14.x is binary-compatible with 0.13.x. This is because public APIs in 0.13.x may have become private in 0.14.0 (but kept for bincompat) and subsequently changed/removed without realizing their purpose. For the record, I'm not aware of such a situation, but it's not impossible.

This is why it is important that libraries check binary-compatibility against _all_ previous versions they intend to stay binary-compatible with. Not just the last release (which unfortunately is what I see many projects doing).

I think that in the long term, circe should "schism" from mono-repo into several smaller repositories for each module. This would allow an individual module to make breaking changes, and publish under a new version, without forcing core to bump its version as well.

See also, http4s which recently went through a similar change.
https://github.com/http4s/http4s/releases/tag/v0.23.12
