### ISSUE TITLE
Can't pattern match Decoders within for-expressions with Scala 3

### ISSUE THREAD

**Issue by nartamonov** [circe/circe#1813]
Since `Decoder`s don't support `withFilter` operation, the following code isn't compiled by Scala 3 because of error `value withFilter is not a member of io.circe.Decoder[(message_store.UserId, record_viewings.VideoId)]`:

```scala
case class VideoViewed(
  id:       EventId,
  metadata: EventMetadata,
  userId:   Option[UserId],
  videoId:  VideoId
)

object VideoViewed:
  given Decoder[VideoViewed] =
    for
      id                <- Decoder[EventId].at("id")
      metadata          <- Decoder[EventMetadata].at("metadata")
      (userId, videoId) <-
        (for
          userId  <- Decoder[UserId].at("userId")
          videoId <- Decoder[VideoId].at("videoId")
         yield (userId, videoId)).at("data")
    yield VideoViewed(id, metadata, userId, videoId)
```

In Scala 2 this issue was solved by [better-monadic-for](https://github.com/oleg-py/better-monadic-for) plugin, but its author isn't planning to rewrite it for Scala 3.

Is it possible to write meaningful implementation of `withFilter` for `Decoder`s?

**Comment by travisbrown** [comment]
I don't have a strong opinion about this. In general I've tried to avoid adding pieces that require arbitrary decisions or additions, but otherwise there's no real reason not to have a `withFilter` with some special `DecodingFailure`.

Personally I don't think `for`-comprehensions are generally the best way to compose decoders. It's relatively rare to have real data dependencies between decoding operations, and using `for` instead of the applicative combinators means you lose the ability to turn on meaningful error accumulation if needed.

So I wouldn't necessarily be opposed to a PR adding `withFilter`, assuming that we can come up with reasonable choices for what filtering failures look like, and that other people are on board.

**Comment by zarthross** [comment]
In Scala 3, you can add the compiler flag `-source:future` and then the code example above compiles.
