### ISSUE TITLE
Map[Boolean, T] fails to encode with 'could not find Lazy implicit value of type DerivedAsObjectEncoder[Foo]'

### ISSUE THREAD

**Issue by praateekmahajan** [circe/circe#1903]
## Build Details
Circe : 0.14.0-M1
Scala : 2.12.10

### Problem 

If there is a case class, with an element that is a `Map` where key is `Boolean`, the encoding fails with an unclear error message
```scala
could not find Lazy implicit value of type io.circe.generic.encoding.DerivedAsObjectEncoder[Foo]
not enough arguments for method deriveEncoder: (implicit encode: shapeless.Lazy[io.circe.generic.encoding.DerivedAsObjectEncoder[Foo]])io.circe.Encoder.AsObject[Foo].
Unspecified value parameter encode.
```

### Code
```scala
import io.circe.Encoder
import io.circe.syntax._
import io.circe.generic.semiauto.deriveEncoder

case class Foo(boolKeyMap: Map[Boolean, String])

object Foo {
  implicit val encFoo: Encoder[Foo] = deriveEncoder[Foo]
}
println(
  Foo(boolKeyMap = Map(true -> "str")).asJson.spaces2
)
```

### Scastie link

https://scastie.scala-lang.org/0PSRfw5JRASQGBEcHyWAhA

### Question

I'm wondering if this is intended behavior and if so, is there scope of improving the error message.

**Comment by zmccoy** [comment]
This is because of a missing `KeyEncoder` for Boolean.  The message is a bit unclear because of how Shapeless ends up working.  Something like https://scastie.scala-lang.org/eMvYNqaxSaW5yjsKU4M4uA would make it compile.  Circe provides some instances for keys that would be used here https://github.com/circe/circe/blob/main/modules/core/shared/src/main/scala/io/circe/KeyEncoder.scala.  

This is currently intended behavior, but there isn't any current work being done to improve that error message.

**Comment by praateekmahajan** [comment]
Makes sense, thanks for sharing the scalstie link, wondering why does the current `KeyEncoder.scala` not have an encoder for `Boolean`, given we have for other primitive data types (Int, Long etc) as well.

**Comment by zmccoy** [comment]
Boolean isn't a very common key for a Map.  A lot of representations would be in my opinion easier with a case class that held two optional values or some other encoding of logic.

**Comment by praateekmahajan** [comment]
Thank you for engaging in the conversation, I agree it's not common and could be better defined in a case class with two values.

For my understanding, would there be a reason to not add the Boolean encoder to `KeyEncoder`? Not common is a good reason that it isn't already there but wondering if it's a good enough reason to not include it further (assuming the time to create and merge the PR is free)?
I see URI in the KeyEncoder which makes me think that's a further rarer key, yet possible key, similarly Boolean, rare key yet possible.

**Comment by zarthross** [comment]
@praateekmahajan I think the problem with us implementing a `Boolean` `KeyEncoder` or `KeyDecoder` is going to be choosing a canonical representation.  For all the key encoder/decoders so far there is a very clear representation to choose, including URI and UUID.  But for boolean, do we go with `TRUE`, `true`, `True`, or `1`?  We cannot choose all of them, because you could have multiple of those keys within a Json Objects.  I think the safest thing for us, as a library would be to let any user who needs a `KeyEncoder[Boolean]` to implement the specific one they want. 

For instance, you could add this next to your encoder and solve your problem, with a bonus decoder too: ([scastie link](https://scastie.scala-lang.org/pMuaRIuFQseMjgfHtsmonw))

```scala
  implicit val encBoolKey: KeyEncoder[Boolean] = KeyEncoder[String].contramap(_.toString)
  implicit val decBoolKey: KeyDecoder[Boolean] = KeyDecoder.instance {
    case "true" => Option(true)
    case "false" => Option(false)
    case _ => None
  }
```
