### ISSUE TITLE
Decoding compilation fails for tagged types with Circe > 0.14.3

### ISSUE THREAD

**Issue by kciesielski** [circe/circe#2135]
Circe 0.14.4 and 0.14.5 break compilation with Scala 3 in Tapir tests. I have isolated the error to a `scala-cli` snippet:

```scala
//> using dep "io.circe::circe-generic:0.14.5"
//> using dep "com.softwaremill.common::tagging:2.3.4"

import io.circe.{Decoder, Encoder}
import io.circe.generic.auto._
import com.softwaremill.tagging._

case class BasketOfFruits(fruits: List[String] @@ BasketOfFruits)

object Main extends App {

  implicit def validatedListDecoder[T: Decoder]: Decoder[List[T] @@ BasketOfFruits] = implicitly[Decoder[List[T]]].map(_.taggedWith[BasketOfFruits])

  def fun1[T: Decoder]: String = "whatever"

  println(fun1[BasketOfFruits])
}
```

It fails with
```
[error] ./Main.scala:16:31
[error] not a constant type: Tuple.Size[mirror$proxy1.MirroredElemTypes]; cannot take constValue
[error]   println(fun1[BasketOfFruits])
[error]        
```
In Tapir we can see some additional stack trace (https://github.com/softwaremill/tapir/actions/runs/4841457066/jobs/8627706404?pr=2769#step:8:557)
```
[error]     |not a constant type: Tuple.Size[mirror$proxy12.MirroredElemTypes]; cannot take constValue
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Default.scala:25
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Default.scala:25
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Default.scala:25
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Default.scala:25
[error]      ---------------------------------------------------------------------------
```

**Comment by MartinHH** [comment]
I looked into this for a bit and learned two things:

a) The root cause (as already indicated by the tapir error above) appears to be that summoning of `io.circe.derivation.Default` (i.e. `io.circe.derivation.Default.mkDefault`) does not work for tagged types. This snippet gives the same error:
```
//> using dep "io.circe::circe-generic:0.14.5"
//> using dep "com.softwaremill.common::tagging:2.3.4"

import com.softwaremill.tagging._

case class BasketOfFruits(fruits: List[String] @@ BasketOfFruits)

object Main extends App {
  io.circe.derivation.Default.mkDefault[BasketOfFruits]
}
```

b) I asked myself: "but why does the code summon something that is related to optional, configurable use of case class default values when the default configuration says `useDefaults: Boolean = false`"?
Turns out that since 0.14.4, all derived Decoders contain a member `lazy val elemDefaults: Default[A] = Predef.summon[Default[A]]`. At runtime, that lazy val is only accessed if `conf.useDefaults` is `true`, but that does not save the compiler from generating the code to summon that instance at compiletime.


So there might be two ways to fix this:

i) make `io.circe.derivation.Default.mkDefault` support tagged types.

ii) find a way to make the compiler not use `io.circe.derivation.Default.mkDefault` if `conf.useDefaults` is `false`.
I guess the following would not work (edit: it doesn't, "Cannot reduce `inline if` because its condition is not a constant value: io.circe.derivation.Configuration.default.useDefaults"), but it might illustrate the idea:
```
lazy val elemDefaults: Default[A] =
  inline if (conf.useDefaults) Predef.summon[Default[A]] else someEmptyDummyDefaults[A]
```

**Comment by MartinHH** [comment]
> a) The root cause (as already indicated by the tapir error above) appears to be that summoning of `io.circe.derivation.Default` (i.e. `io.circe.derivation.Default.mkDefault`) does not work for tagged types.  [...]

Isolating the problem some more, it comes down to this (which fails to compile with the same error, but compiles (and prints 1) if removing the `@@ BasketOfFruits` tag):

```
//> using dep "com.softwaremill.common::tagging:2.3.4"

import com.softwaremill.tagging._

import scala.compiletime.*
import scala.deriving.*

transparent inline def membersCount[T](using mirror: Mirror.Of[T]) =
  constValue[Tuple.Size[mirror.MirroredElemTypes]]

case class BasketOfFruits(fruits: List[String] @@ BasketOfFruits)

object Main extends App {
  println(membersCount[BasketOfFruits])
}
```

Changing the way to obtain the value of `Tuple.Size[mirror.MirroredElemTypes]` a bit gave a different, probably more helfpul error:
```
//> using dep "com.softwaremill.common::tagging:2.3.4"

import com.softwaremill.tagging._

import scala.compiletime.*
import scala.deriving.*

transparent inline def membersCount[T](using mirror: Mirror.Of[T]) =
  summonInline[ValueOf[Tuple.Size[mirror.MirroredElemTypes]]].value

case class BasketOfFruits(fruits: List[String] @@ BasketOfFruits)

object Main extends App {
  println(membersCount[BasketOfFruits])
}
```
...gives:
```
[error] No singleton value available for Tuple.Size[mirror$proxy1.MirroredElemTypes]; eligible singleton types for `ValueOf` synthesis include literals and stable paths.
[error] 
[error] Note: a match type could not be fully reduced:
[error] 
[error]   trying to reduce  Tuple.Size[mirror$proxy1.MirroredElemTypes]
[error]   failed since selector  mirror$proxy1.MirroredElemTypes
[error]   is uninhabited (there are no values of that type).
[error]   println(membersCount[BasketOfFruits])
[error]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error compiling project (Scala 3.3.0, JVM)
```

**Comment by MartinHH** [comment]
> So there might be two ways to fix this:
> 
> i) make `io.circe.derivation.Default.mkDefault` support tagged types.

Turns out there's a trivial way to do that (see pull request).
