### ISSUE TITLE
DecodingFailure(CNil, List()) exception during deserialization of sealed trait

### ISSUE THREAD

**Issue by plavreshin** [circe/circe#349]
Hi all, 

I have following simple hierarchy of case classes extending sealed trait:

```
 sealed trait Client 
 case class Subscribe(token: String) extends Client
 case class Ping(clientTime: Long) extends Client
```

When I try to serialize and deserialize above mentioned case classes, deserialization fails with an exception `DecodingFailure(CNil, List())` :

```
  "simple test" in new TestScope {
      val in: Subscribe = Subscribe(token = "token")
      val json = in.asJson.noSpaces

      val result = decode[Client](json)
      result match {
        case Xor.Right(out) => out mustBe in
        case Xor.Left(f) => fail(s"failure: $f")
      }

```

Circe-json version is 0.4.1. 

Could you please be so kind as to advice on this issue ?

**Comment by travisbrown** [comment]
Hi @plavreshin! By default the representation of the leaves of an ADT are different from the representation of the root, so `(in: Client).asJson` will be `{ "Subscribe": { "token": "token" }}`, while `in.asJson` will be just `{ "token": "token" }` (i.e. the JSON depends on the static type of `in`).

This is by design, but it's not always what you want. In your case statically typing `in` as `Client` would work, or decoding into `Subscribe` instead of `Client`, or you could provide your own codecs that treat the two levels the same.

I'd be happy to give more information about these options—let me know which would be closest to what you're looking for.

**Comment by plavreshin** [comment]
hi @travisbrown  and thanks a lot for prompt reply and explanation. My use case is that I am trying to use shared domain classes between Scala.js frontend and Play2 backend, using circe-json for serialization/deserialization.

I would prefer to deserialize json to `sealed trait`  for further pattern matching, for instance like this:
```
def receive = {
    case msg: String => decode[Client](msg) match {
      case Xor.Right(cmd) => cmd match {
        case x: Subscribe => onSubscribe(x)
        case x: Ping => onPing(x)
        case x: Query => onQuery(x)
      }
      case Xor.Left(f) => logger.error("Failed to deserialize: $msg")
    }
```

Could you please advice on custom codecs for sealed trait based (de)-serialization with least amount of boilerplate ?

Would it help to define sealed trait as: 

```
sealed trait Client {
  def typ: String
}

case class Subscribe(token: String) extends Client {
  def typ: String = "cmd.subscribe"
}
``` 
and write own custom codecs and match against `typ` field ?
