### ISSUE TITLE
Long value incorrectly decoded on Scala.js

### ISSUE THREAD

**Issue by tindzk** [circe/circe#393]
The following test case fails on Scala.js:

``` scala
import cats.data.Xor
import io.circe.generic.auto._
import io.circe.parser._
import io.circe.syntax._

val num = 767946224062369796L
val json = num.asJson.noSpaces
assert(decode[Long](json) == Xor.Right(num))
```

**Comment by travisbrown** [comment]
Thanks @tindzk—I'll take a closer look at this, but at a glance I think [this](https://travisbrown.github.io/circe/api/index.html#io.circe.Decoder$@decodeBigDecimal:io.circe.Decoder[BigDecimal]) is what you're seeing:

> Also note that because `scala.scalajs.js.JSON` parses JSON numbers into a floating point representation, decoding a JSON number into a `BigDecimal` on Scala.js may lose precision.

Could you try `decode[JsonNumber]` and then `toLong` as a workaround?

**Comment by tindzk** [comment]
Thanks! I tried the following code:

```scala
import io.circe._
import io.circe.parser._

println(767946224062369796L)
println(decode[Long]("767946224062369796"))
println(decode[JsonNumber]("767946224062369796"))
println(decode[JsonNumber]("767946224062369796").map(_.toLong))
```

Here is the JVM output:
```
767946224062369796
Right(767946224062369796)
Right(767946224062369796)
Right(Some(767946224062369796))
```

Unfortunately, it behaves differently on Scala.js:
```
767946224062369796
Right(767946224062369792)
Right(767946224062369800)
Right(Some(767946224062369792))
```

**Comment by jonas** [comment]
The problem is that circe uses [`JSON.parse`](https://github.com/circe/circe/blob/991aaf596693acd9c35d400a845577232030b797/modules/parser/js/src/main/scala/io/circe/parser/package.scala#L9) parsing and decoding in Scala.js. When circe gets to [convert to its AST](https://github.com/circe/circe/blob/4fe187a123183cac09b0a7edf060c6eda689c979/modules/scalajs/src/main/scala/io/circe/scalajs/package.scala#L14) the damage is already done.

```javascript
> JSON.parse("767946224062369796")
767946224062369800
> JSON.parse("767946224062369796").toFixed()
"767946224062369792"
> JSON.parse("767946224062369796").toPrecision()
"767946224062369800"
```

I will make a PR to document the current behaviour.

The only way to fix this would be to include a "custom" JSON parser for Scala.js and let users choose between performance or correctness.

**Comment by travisbrown** [comment]
@jonas @tindzk I've just been thinking about this in conjunction with #476.

The idea would be that the fallback string decoder for numeric types would use circe's own number parser. That way Scala.js users would get the default JavaScript JSON parsing for ordinary JSON numbers, but if they wanted more precision they could represent their numbers as strings.

To me this seems less invasive than entirely changing the way JSON numbers are handled natively in JavaScript. The inconsistency isn't ideal, but I think that's part of the price we have to pay to work on a platform without nice numbers. (Not that the JVM is that much better. :smile:).

**Comment by jonas** [comment]
Yes, that is a good point. So some kind of `Configuration.withStringlyTypedNumerics`?

**Comment by travisbrown** [comment]
@jonas This would actually be the default, for both the JVM and Scala.js. It fixes the inconsistencies noted in #476, while also allowing Scala.js users to get more precision by representing their numbers as strings.

**Comment by jonas** [comment]
OK, will there be an option to turn it off when interoperability is needed?

**Comment by travisbrown** [comment]
@jonas When would that be necessary? Just to clarify, the decoding of `{ "n": 767946224062369796 }` as a `Long` would remain the same (i.e. wrong) on Scala.js—you'd only get the improved behavior with `{ "n": "767946224062369796" }`.

**Comment by tindzk** [comment]
I'm not sure whether having custom behaviour in the decoding process is a good idea. I am concerned it will impact interoperability with other JSON libraries. Wouldn't it be better not to create invalid JSON in the first place? I suppose the standard imposes restrictions on the precision of numbers. So, `asJson` could fail if a number cannot be possibly represented in JSON.

**Comment by travisbrown** [comment]
@tindzk The issue is that the JSON standard doesn't put any restrictions on precisions—a JSON number can be as precise as you can fit in a string in memory (or more, I guess). The restrictions come from JavaScript, which in many cases isn't involved as a platform at all when working with JSON.

The behavior proposed in #476 doesn't customize JavaScript's JSON parser on Scala.js—it's entirely about decoding, and in my experience it's in line with other libraries in this respect. Representing numbers as strings when you need a lot of precision isn't uncommon—Jackson does it, other JavaScript stuff does it, etc. In circe I've done my best to make this unnecessary, and to make interoperability with libraries that do choose that route as easy as possible, and I think this is just an extension of that effort for Scala.js.

**Comment by tindzk** [comment]
I see. Thanks for the clarifications. As @jonas suggests, an option for disabling this behaviour would still be desirable. I imagine the case where a developer wants to parse JavaScript-generated JSON and parse it in Circe. The decoding process should fail if Circe sees a string instead of a number.

**Comment by travisbrown** [comment]
@tindzk Would you mind opening a separate issue for that? Since the beginning, circe (like Argonaut) has silently fallen back to attempting to parse JSON strings as numbers during decoding for numeric types—#485 just makes this a little more robust (and more consistent on the JVM side).

You could do the extra validation you propose right now with `prepare` on the decoder, but if there's enough demand for built-in support (as an option, not the default) I'd be happy to add it.

**Comment by tindzk** [comment]
Thanks for fixing the bug! I created an issue as requested.

**Comment by armanbilge** [comment]
For anyone running into this issue, as of v0.14.2 you can use the cross-platform `circe-jawn` parser on both JVM and JS (instead of `circe-parser`). The `circe-jawn` parser does not exhibit the problem reported in this issue, and generally will have the same semantics on both the JVM and JS.

I hope this might because the default parser in the future, see:
- https://github.com/circe/circe/issues/1941
