### ISSUE TITLE
Move circe-spray to its own project

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#514]
circe-spray is now the only published module that we can't build for 2.12, and since Spray seems to be more or less unmaintained at this point I think it makes sense to split circe-spray into its own project.

The result would look similar to what I've just done for [circe-jackson](https://github.com/circe/circe-jackson). I'd prefer to maintain history, so the first step would be a fresh clone of this repo and then something like this:

```bash
git filter-branch --subdirectory-filter modules/spray/
```

Once this is done I'd probably vote to de-aggregate `hygiene` and `benchmark` and get rid of sat-doge altogether.

**Comment by ktoso** [comment]
Hi there, correct Spray is nearing end of life and we'd only release it for fixing security or similar issues. The "Spray 2.0" as we sometimes call it is Akka HTTP, so one could ask if circe should include akka-http-circe instead. 

However it seems that this module was just to integrate with the marshalling infrastructure?
If so, then no additional work from you guys is needed since this is supported in: https://github.com/hseeberger/akka-http-json/tree/master/akka-http-circe already.

Just making sure you have all information you may need for next steps :)
The moving out sounds good too, as it likely won't see a Scala 2.12 release.

**Comment by travisbrown** [comment]
@ktoso Yep, akka-http-circe is great. I've kept circe-spray around because plenty of people are still using Spray (including me, unfortunately), and since it has some features that aren't yet in akka-http-circe (like convenient error accumulation). Moving it to a separate project would be a way to continue supporting it, but without having it complicate the build for circe itself.

**Comment by ktoso** [comment]
Yup, makes sense :-)

**Comment by travisbrown** [comment]
@ktoso By the way thanks for the reminder that I've been meaning to open an issue like this: https://github.com/hseeberger/akka-http-json/issues/114 :smile:

**Comment by n4to4** [comment]
@travisbrown
I'm not so sure if everything is okay, but here's what I've got.
https://github.com/n4to4/circe-spray

**Comment by travisbrown** [comment]
@n4to4 Wow, that was fast! Looks good to me—I'll set up circe/circe-spray and make you a co-maintainer.

**Comment by travisbrown** [comment]
Done ([here](https://github.com/circe/circe-spray) and [here](https://github.com/circe/circe/pull/519)). Thanks again @n4to4!
