### ISSUE TITLE
Automatically publish site on each merge

### ISSUE THREAD

**Issue by jonas** [circe/circe#531]
As discussed a while back on the Gitter channel it would be nice to automatically publish documentation either when PRs are merged or when tags are created. To avoid having the `gh-pages` branch inside circe/circe the site should be hosted in circe/circe.github.io that could eventually be served via circe.io (which BTW still points to travisbrown/jfc ;) ).

The approach I am suggesting for this is documented in [this gist](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd). In short, Travis CI will publish using an SSH deploy key which must be added to the target repository. I am currently working on documentation of the process for sbt-site so this can either be done by one of the repo owners when that is done or alternatively if you don't mind me fiddling with SSH deploy keys for the new circe.github.io repo I would also be happy to do it.

We should probably also discuss whether some of the other circe repos need to publish API docs.

**Comment by travisbrown** [comment]
Ugh, just lost a several paragraph draft response to a browser crash.

In short for now—I agree that we should start publishing on every PR, now that more work is happening on the site. I'm not entirely convinced that the circe site itself should live directly under https://circe.github.io/, though—I had a conversation with @dwijnand about this a couple of weeks ago at Scala Exchange and he mostly convinced me that it makes the most sense to have https://circe.github.io/ be a landing page and introduction with the circe site remaining under https://circe.github.io/circe/. I'm happy to discuss pros and cons, though.

I would like to use the circe.io domain instead of circe.github.io (and by the way I just fixed the redirect—thanks for catching that 😄). Do you happen to know if it's possible to use a custom domain with multiple projects, @jonas?

About other circe org projects—circe-spray and circe-jackson both already have published API docs. I don't think circe-yaml does, but it probably should (I've leave that up to @jeremyrsmith and @jeffmay, but I'm happy to help).

**Comment by jonas** [comment]
With a GitHub org site (and custom domain) you can mix and match how org projects host their docs. If circe-yaml has a gh-pages branch it will take effect else HitHub pages will try to resolve the path in the org site. The trick is to make Travis CI do a shallow clone of the org site and then only update files in the org project's subdirectory of the site.

**Comment by jonas** [comment]
Status update: Documentation for sbt-site and publishing with SSH keys has been completed and tested: http://www.scala-sbt.org/sbt-site/publishing.html#publishing-to-github-pages-from-travis-ci

Will start looking into how to publish into a shared org site.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
