### ISSUE TITLE
implicit decoder in scope makes Decoder[A] return null using generic.auto._

### ISSUE THREAD

**Issue by valenterry** [circe/circe#575]
Not sure if this is a circe specific issue or a more general one. See fiddle: https://scalafiddle.io/sf/35RxpkJ/0

``` 
case class User(name: String, int: Int)

import io.circe._
import io.circe.generic.auto._

val decoder: Decoder[User] = Decoder[User]

//Toggle me!:
implicit val decoderImplicit: Decoder[User] = decoder

println(decoder)
``` 

Executing this code will result in `Decoder[User]` returning `null` and thus `decoder` will be `null`. However, if we comment out the `implicit val decoderImplicit: Decoder[User] = decoder`, then `Decoder[User]` returns a valid and working `Decoder[User]`.

Lifting the implicit decoder into its own scope via `{ implicit val decoderImplicit: Decoder[User] = decoder }` has the same effect as commenting it out. Removing the type annotions also works - even though the types are the same.

**Comment by knutwalker** [comment]
This is an unfortunate restriction of Scala itself, not limited to circe. `Decoder[User]` is defined as `def apply[A](implicit instance: Decoder[A]): Decoder[A] = instance`, so it's not doing any work, it's just searching for the "nearest" implicit instance of a `Decoder[User]` an returns that.
The `implicit val decoderImplicit: Decoder[User]` is such a valid definition; it is implicit, in the current scope and has the proper type, though it's definition uses the value that is currently in the process of being initialized, that is, which is not yet initialized and therefore null (The same would happen if you inline `decoder` to `implicit val decoderImplicit: Decoder[User] = Decoder[User]`).
The main issue here is, that the compiler allows for not initialized fields or values to be a valid implicit search result, because it's annotated with the targeted result type. 
Omitting this type leaves the compiler guessing whether the type might eventually fit and since it's not yet initialized and thus its type not inferable, it doesn't participate in the implicit search.

A good workaround in circe is to use `semiauto`:

```
case class User(name: String, int: Int)

import io.circe._
import io.circe.generic.semiauto._

val decoder: Decoder[User] = deriveDecoder

implicit val decoderImplicit: Decoder[User] = decoder

// also works inlined
implicit val decoderImplicit: Decoder[User] = deriveDecoder
```

**Comment by travisbrown** [comment]
Thanks for the excellent explanation, @knutwalker (we really should have a FAQ entry for this). @valenterry, does that cover the issue for you?

**Comment by valenterry** [comment]
Yes, absolutely, thank you!
