### ISSUE TITLE
Error handling with optics

### ISSUE THREAD

**Issue by s12v** [circe/circe#583]
When I define a path with optics (i.e. `root._source.as[Document]`), I can call `getOrElse(json)` which gives me a `Document` or `None` in case it was not able to.

My question is how do I get the error? In case of `None` I can understand that something went wrong, but what exactly? Something like `json.hcursor.get[Document]("_source")` - is there similar functionality in optics?

**Comment by briantopping** [comment]
I'm having a similar issue:
```
  val json                      = parse(File("../issues.json").slurp).getOrElse(Json.Null)
  val ids: immutable.Seq[Issue] = root.each.as[Issue].getAll(json)
```
The first line returns 40 JSON elements, the second line ends up with 23 elements in the sequence.

**Comment by travisbrown** [comment]
I'm going to go ahead and close this issue, unfortunately, since this is an inherent limitation of Monocle that we can't really work around in circe (in that [Monocle only gives us a yes or no answer](https://groups.google.com/d/msg/scala-monocle/eypLMKy1bbw/wT8xpBGzWewJ) via `Option`).

[Goggles](https://github.com/kenbot/goggles/) is built on Monocle and might provide some pieces you want, but I think in general if you want this kind of functionality circe's own cursor API is your best bet.

**Comment by briantopping** [comment]
Thanks for all your great work on this!
