### ISSUE TITLE
Allow customization of the error message for missing element when decoding

### ISSUE THREAD

**Issue by backuitist** [circe/circe#588]
Currently decoding a JSON that misses an element will result in a `DecodingFailure` with a message saying: `"Attempt to decode value on failed cursor"`.
This error cannot be customized other than by doing string matching on `DecodingFailure.message`.
I would suggest to add a default parameter on `decode` and `decodeAccumulating`:
```scala
final def decode[A: Decoder](input: String, missingElementErrorMessage: String =
                             defaultMissingElementErrorMessage)
``` 

An alternative would be to encode that case in the type:
```scala
sealed trait DecodingFailure { def history: List[CursorOp] }
case class MissingElement(val history: List[CursorOp]) extends DecodingFailure
case class IncorrectValue( /* ... */ ) extends DecodingFailure
```

**Comment by knutwalker** [comment]
Maybe this might help; I did change the message by looking at the cursor history and trying to examine whether the failure was due to a missing field (which could be simplified a bit by using CursorOp.opsToPath):
https://github.com/knutwalker/akka-stream-json/blob/b8bc752ef3ab2f76793c0db40bddc8a2bd5787df/support/stream-circe/src/main/scala/de/knutwalker/akka/stream/support/CirceStreamSupport.scala#L46-L73

**Comment by backuitist** [comment]
Ok, but it's a bit of a waste to have to go through the JSON cursor again, basically duplicating the logic of the Decoder just to surface that information (the fact that the element was missing). I believe circe should provide that information.
I'll add an alternative to the issue.

**Comment by knutwalker** [comment]
@backuitist I agree, a first class solution would be better, it was more meant as a in-the-meantime thing different from string matching.

**Comment by travisbrown** [comment]
Thanks, @backuitist. I agree that we need a better solution here. My inclination would be to have the `DecodingFailure` be aware of whether the last operation in the history (i.e. the head of `history`, which is in reverse chronological order) failed or now, which should give us all the info we need to provide nicer messages. What do you think?

**Comment by backuitist** [comment]
@travisbrown is it valid to conclude that if the last operation in the history is a failure, we have a missing element? In that case what do you think of the alternative described in the first message (refining the `DecodingFailure` into `MissingElement` or `IncorrectValue`)? That might be a breaking change though.

**Comment by travisbrown** [comment]
@backuitist Well, specifically a failed `downField` would indicate a missing field.

I'd like the `DecodingFailure` _representation_ to be as interpretation-free as possible—to say "I was doing this thing and then I failed in this way", not "you're missing this field" (although a message like that might be provided as a convenience operation).

Maybe that's not incompatible with your proposal, though, since you can imagine all failures being divided into either navigation failures ("I couldn't get where I was going") or invalid value failures ("I got there but didn't find what I needed").

I'm happy to make breaking changes as long as they don't drastically affect normal usage. I'd like to think about it a little more, though, and to collect any other ideas.

**Comment by backuitist** [comment]
@travisbrown completely agree. The Navigation vs invalid value dichotomy sounds good :)
Thanks for thinking about it.

**Comment by backuitist** [comment]
@travisbrown Any further thoughts?

**Comment by travisbrown** [comment]
@backuitist Sorry, I've not had a lot of time to work on circe in the past couple of weeks, and what I have had has been spent on some number-related fixes. I'm planning to publish 0.8.0 within a couple of days (after an 0.7.1 today), so I think we'll need to push this to 0.9.

I'd definitely be receptive to a PR, although I'm happy to work on it myself when I get time. Thanks for checking in.

**Comment by nadavwr** [comment]
We're migrating from play-json to circe, and this is one thing we'll sorely miss—a detailed report of all missing fields

**Comment by exoego** [comment]
I opended a PR #1081 to implement this feature, but no response for 3 months.
If it is unlikely to be implemented in circe, please close this issue as wontfix.
