### ISSUE TITLE
Coursier chokes on Scala.js

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#625]
When trying to run the tests in `tests` on Scala.js I'm seeing the following errors:

```
[info] Compiling 35 Scala sources to /home/travis/code/projects/circe/modules/tests/js/target/scala-2.12/test-classes...
java.lang.RuntimeException: Illegal classpath entry: /home/travis/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.2/scala-library-2.12.2.pom
	at scala.sys.package$.error(package.scala:27)
        ...
```
This is happening for all Scala versions, but not all tests—the `optics` tests run just fine on Scala.js, for example.

Removing Coursier from the build temporarily fixes the issue, and since we generally only run Scala.js tests before releases, I have very little interest in spending time thinking about this, but if anyone wants to help it'd be much appreciated. 😄

**Comment by alexarchambault** [comment]
This is addressed in the current master of coursier since [this commit](https://github.com/coursier/coursier/commit/13da5e871f28aaa380d63f0268e9b2585b624ba7), which removes the POMs from the `update` report.

There's still possibly an issue on the scalajs side though IMO (it should filter artifacts - sbt itself filters them with the `classpathTypes` setting for example), but you should be fine from the circe repo.

**Comment by travisbrown** [comment]
Great, thanks @alexarchambault!

**Comment by travisbrown** [comment]
Resolved after updating to more recent Coursier release candidates.
