### ISSUE TITLE
Include Java 8 time codecs in core for Scala 2.12

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#732]
Since Scala 2.12 requires Java 8 it might make sense to have a version-specific trait mixed into the `Decoder` companion object that would provide the `java.time` codecs there (without a separate dependency / import). I think with the right SBT magic we could do this without (much) code duplication.

**Comment by gpoirier** [comment]
I created a PR for this ticket. Hopefully that's what you had in mind. I should note that the time codecs are a cut-n-paste from the time project but split in two different traits to be mixed in `Encoder` and `Decoder`. The only change that was made was to change some of the `val` to `def` because it was breaking the serialization tests for the other codecs, since `DateTimeFormatter` is not serializable.

**Comment by gpoirier** [comment]
I'm just realizing a potential issue. I didn't remove the java8 project, and it might still be useful for people that wants to use java.time on Scala 2.11 with jdk8. However, I'm not sure how to share the code between core and java8. May be the best fix is to leave the time codecs in the shared sources, and use an additional trait to have it mixed in `Encoder` and `Decoder` only in Scala 2.12. Having the time codec instances shouldn't cause in the jars shouldn't cause issue in jdk7 if they aren't mixed in `Encoder` and `Decoder` I assume?

**Comment by gpoirier** [comment]
I just tried the approach described above, but it seems to fail with scalajs, so it might not be possible to include time codecs at all in the Scala 2.10 and Scala 2.11 code base, even if they are not mixed in `Encoder` and `Decoder` objects?

**Comment by travisbrown** [comment]
Done in #754 and #945.
