### ISSUE TITLE
io.circe.generic.extras missing in 0.9.x !?

### ISSUE THREAD

**Issue by hansschl** [circe/circe#846]
I want to use custom key mappings (as described in https://circe.github.io/circe/codec.html#custom-key-mappings-via-annotations) with circe 0.9.0 and 0.9.1 but with both compilation fails due to missing package "io.circe.generic.extras".
Ive created project and libs with sbt:

    val circeVersion = "0.9.1"
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-core",
      "io.circe" %% "circe-generic",
      "io.circe" %% "circe-java8",
      "io.circe" %% "circe-parser"
    ).map(_ % circeVersion)

Am I missing something? Thanks!

**Comment by travisbrown** [comment]
@hansschl The `io.circe.generic.extras` package is available in the circe-generic-extras artifact, which is separate from the circe-generic artifact because of its more experimental status. Among other things, circe-generic will always be versioned with circe-core, while circe-generic-extras may have its own versioning after 1.0.

If you change the `"io.circe" %% "circe-generic"` line to `"io.circe" %% "circe-generic-extras"`, does your code compile?

**Comment by hansschl** [comment]
Travis, yes that solves my issue. Great. Thanks a lot!

**Comment by travisbrown** [comment]
@hansschl Glad to hear it!
