### ISSUE TITLE
Json return Some(null) after data read

### ISSUE THREAD

**Issue by patrykpacewicz** [circe/circe#892]
Hi, today I was using circle and I notice that

```scala
@ Json.fromString(null)
res1: Json = JString(null)
@ Json.fromString(null).asString
res2: Option[String] = Some(null)
```

That `Some(null)` looks like a bug. It is something that is very hard to work with. No one suspect `null` inside `Some`, after that you are looking for a bug in your code for couple hours :-)

IMHO the correct result should be

```scala
@ Json.fromString(null).asString
res1: Option[String] = None
```

or something like that:

```scala
@ Json.fromString(null)
res1: Json = JNull
```

**Comment by travisbrown** [comment]
The current contract here is that if you pass `null` as an argument to _any_ method in the circe API, the behavior is undefined, but you will almost certainly end up with a null pointer exception, which is what happens in your case in an ordinary Scala REPL (or when you try to call `noSpaces` or `toString` or most other methods on the `Json` value):

```scala
scala> io.circe.Json.fromString(null)
java.lang.NullPointerException
  at io.circe.Printer$PrintingFolder.onString(Printer.scala:272)
  at io.circe.Printer$PrintingFolder.onString(Printer.scala:256)
  at io.circe.Json$JString.foldWith(Json.scala:299)
  ...
```

Note that this happens lazily, so the following for example won't throw the exception:
```
scala> object Foo { val x = io.circe.Json.fromString(null) }
defined object Foo
```
Instead it would show up when you try to print `x`:
```scala
scala> Foo.x
java.lang.NullPointerException
  at io.circe.Printer$PrintingFolder.onString(Printer.scala:272)
  at io.circe.Printer$PrintingFolder.onString(Printer.scala:256)
  at io.circe.Json$JString.foldWith(Json.scala:299)
  ...
```
You're seeing `JString(null)` only because Ammonite is using its own pretty-printer for case classes instead of respecting the `toString` on `io.circe.Json`. I don't particularly like this behavior in Ammonite, and don't care to make special accommodations for it in circe (although I guess we could consider it if there's enough demand).

The problem with changing the behavior in the way you describe is that adding null-checking feels like a slippery slope. My personal position is that while a purely functional library like circe should never introduce NPEs (or similar exceptions) into your code, it's also not the responsibility of the library to handle these exceptions if you drag them in. Ideally you would check for nulls at the boundary of your program (where you call Java APIs, etc.), and they would be long gone by the time you get to a level where you're working with circe.
