### ISSUE TITLE
ADT auto-derivation in Generic Extras doesn't work with intermediate traits

### ISSUE THREAD

**Issue by benhutchison** [circe/circe#926]
Concerns the [ADT full auto-derivation feature](https://circe.github.io/circe/codecs/adt.html#the-future):

I find it works for simple sealed trait hierarchies, but when the ADT contains an intermediate trait, it breaks. Intermediate traits in ADTs can be useful to give a type that refer to several items in the ADT, such as all the successful cases.

```
scala> import io.circe.generic.extras.auto._
import io.circe.generic.extras.auto._

scala> import io.circe.generic.extras.Configuration
import io.circe.generic.extras.Configuration

scala> implicit val genDevConfig: Configuration =
     |   Configuration.default.withDiscriminator("what_am_i")

scala> sealed trait Works; case object Works1 extends Works
defined trait Works
defined object Works1

scala> implicitly[Encoder[Works]]
res1: io.circe.Encoder[Works] = io.circe.generic.extras.encoding.ConfiguredObjectEncoder$$anon$2@10a6b021

scala> sealed trait NotWorks; trait InBetween extends NotWorks; case object NotWorks1 extends InBetween
defined trait NotWorks
defined trait InBetween
defined object NotWorks1

scala> implicitly[Encoder[NotWorks]]
<console>:24: error: could not find implicit value for parameter e: io.circe.Encoder[NotWorks]
       implicitly[Encoder[NotWorks]]
                 ^
```

**Comment by travisbrown** [comment]
@benhutchison Sorry for the long delay in responding, but a couple of things:

- `shapeless.LabelledGeneric[NotWorks]` doesn't compile here, so it's something we'd consider out of scope for circe-generic(-extras), since we only derive instances for things that Shapeless provides generic representations for.
- The good news is that if `InBetween` is sealed, Shapeless does provide a generic representation for `NotWorks`, and circe-generic(-extras) will happily derive encoders and decoders. This kind of makes sense, because without the `sealed` modifier all the way down, we could introduce new subclasses of `NotWorks` (which is weird, but that's Scala for you).  

I'm closing this but feel free to reopen if you're not convinced by the above.
