### ISSUE TITLE
Covariance for A of Encoder[A]/Decoder[A]

### ISSUE THREAD

**Issue by aiya000** [circe/circe#943]
I wish covariance for it :smiley:

I wrote like a below code

```scala
sealed trait X
case class A(i: Int) extends X
case class B(i: Int) extends Y

object A {
    val encoder: Encoder[A] = ...
    val decoder: Decoder[A] = ...
}

object B {
    val encoder: Encoder[B] = ...
    val decoder: Decoder[B] = ...
}

type Foo[T] = ...

def f(x: String): Encoder[X] = x match {
    case "give-me-A" => A.encoder
    case _ => B.encoder
}
```

but this is not allowed :joy:

How about if you support `Encoder[+T] / Decoder[+T]`? 🤔 

https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Encoder.scala#L17

I can make PR if it is OK.

**Comment by travisbrown** [comment]
Hi @aiya000! The problem is that `Encoder` isn't covariant (it's contravariant). If you have an `Encoder[A]`, that doesn't mean you have an `Encoder[X]`. For example, what should `A.encoder.apply(B(10))` return? `A.encoder` can be defined without any reference to `B`, so there's no reason it should know what to do with a `B` here.

There's more generally a question whether the type parameters on `Encoder` and `Decoder` should be contravariant and covariant respectively. Right now they aren't, for a number of practical and historical reasons, but at some point in the future they may be. In the meantime you can use the `.narrow` and .widen` methods provided by Cats (via `import cats.syntax.covariant._` and import cats.syntax.functor._`) to perform these (entirely safe) casts manually.

**Comment by aiya000** [comment]
Hi @travisbrown 😄 
Sorry, I had misunderstood.
Thank you for teaching! I really understood 👍
