### ISSUE TITLE
 Null decodings

### ISSUE THREAD

**Issue by yudzhadobin** [circe/circe#955]
Hello!

I've observed some strange behavior with null in incoming json.
My dependencies are:

```
compile group: 'io.circe', name: 'circe-parser_2.12', version: '0.10.0-M1'
compile group: 'io.circe', name: 'circe-core_2.12', version: '0.10.0-M1'
compile group: 'io.circe', name: 'circe-generic_2.12', version: '0.10.0-M1'
compile group: 'io.circe', name: 'circe-generic-extras_2.12', version: '0.10.0-M1'
```
Worksheet: I have 2 case classes, one with Int, another wit Double. 
```
import io.circe.generic.extras.Configuration
import io.circe._, io.circe.generic.semiauto._
import io.circe.parser._

implicit val customConfig: Configuration = Configuration.default.withDefaults

case class IntFoo(a: Int)
case class DoubleFoo(a: Double)
implicit val doubleFooDecoder: Decoder[DoubleFoo] = deriveDecoder[DoubleFoo]
implicit val intFooDecoder: Decoder[IntFoo] = deriveDecoder[IntFoo]

val json = parse(
"""
|{
| "a" : null
|}""".stripMargin
).right.get`
```
Trying to decode: 
```
intFooDecoder.decodeJson(correctJson) // Left(DecodingFailure(Int, List(DownField(a))))
doubleFooDecoder.decodeJson(correctJson) // Right(DoubleFoo(NaN))

```

So while I was trying to decode into Int, I was getting an Exception (the behavior I've expected). But when I tried to decode into Double, everything was OK and it was decoding as NaN (this behavior is strange). 

So, that was the behavior that's expected orr it is bug and it will be fixed?

**Comment by travisbrown** [comment]
This is the expected behavior. In circe encoders can't fail, and circe has a strict no-throwing-exceptions rules, so we have to do _something_ with `Encoder[Double].apply(Double.NaN)`, and a JSON null is the closest thing to a standard encoding of `NaN`. The `Double` decoder recognizes this encoding to keep things round-trippable.

This isn't an issue for `Int`, since the `Int` type doesn't have any non-number inhabitants.

You could write a custom `Encoder[Double]` that did something else in this situation (throw an exception, encode `NaN` as a string or zero, etc.).

**Comment by RoniFinTech** [comment]
How do I set circe to ignore keys whose value is null? 
I need to eliminate the key all together instead of showing null or None...

**Comment by dzikowski** [comment]
You can use `dropNullValues`, e.g. `obj.asJson.dropNullValues.noSpaces`
