### ISSUE TITLE
Serialize case class body fields to json

### ISSUE THREAD

**Issue by yadavan88** [circe/circe#997]
I want to serialize body fields of a case class to json. I am unable to find the way to do it in Circe.
Could anyone please help me with this ?

I have posted this question in SO [here](https://stackoverflow.com/questions/52961669/circe-serialize-case-class-body-fields-to-json/52962934#52962934) but didnt get the required answer. 

I was previously using Json4s and was using the FieldSerializer to get it done.

**Comment by travisbrown** [comment]
Can you show what you've tried?

**Comment by yadavan88** [comment]
Did you mean with Circe ? 
I was not able to find any way to get this. 

I have used the auto decoding.

```

trait NamedEntity {
    def name:String
}

case class EntityWithBodyParams(id:Long) extends NamedEntity {
  override val name:String = "Name"
}

case class AnotherEntity(id:Long, name:String) extends NamedEntity 
```

```
"serialize with body-fields of a case class" in {
      val entity = EntityWithBodyParams(100)
      val json = entity.asJson
      val name = json.\\("name")
      println(json.toString())
      name.size shouldBe 1
      name.head.asString should not be empty
    }
```

In Json4s, I added fieldSerializer for my trait (NamedEntity)

**Comment by yadavan88** [comment]
@travisbrown Could you please guide me in the right direction? I am unable to migrate to circe due to this issue ? Is it not possible ?

**Comment by travisbrown** [comment]
@yadavan88 circe-generic uses Shapeless's generic representation of Scala's case classes and sealed trait hierarchies, and this representation does not include `name` for `EntityWithBodyParams`. You can write a custom encoder and decoder:

```scala
scala> import io.circe.{ Decoder, Encoder }
import io.circe.{Decoder, Encoder}

scala> implicit val encodeEntityWithBodyParams: Encoder[EntityWithBodyParams] =
     |   Encoder.forProduct2("id", "name")((ewbp: EntityWithBodyParams) =>
     |     (ewbp.id, ewbp.name)
     |   )
encodeEntityWithBodyParams: io.circe.Encoder[EntityWithBodyParams] = io.circe.ProductEncoders$$anon$2@6d8b8ad

scala> implicit val decodeEntityWithBodyParams: Decoder[EntityWithBodyParams] =
     |   Decoder.forProduct2("id", "name")((id: Long, _: String) =>
     |     EntityWithBodyParams(id)
     |   )
decodeEntityWithBodyParams: io.circe.Decoder[EntityWithBodyParams] = io.circe.ProductDecoders$$anon$2@97ad7da
```
And then:
```scala
scala> import io.circe.syntax._
import io.circe.syntax._

scala> EntityWithBodyParams(100)
res0: EntityWithBodyParams = EntityWithBodyParams(100)

scala> val entity = EntityWithBodyParams(100)
entity: EntityWithBodyParams = EntityWithBodyParams(100)

scala> entity.asJson.noSpaces
res1: String = {"id":100,"name":"Name"}

scala> io.circe.jawn.decode[EntityWithBodyParams](res1)
res2: Either[io.circe.Error,EntityWithBodyParams] = Right(EntityWithBodyParams(100))
```
…but there's a reason circe doesn't provide an instance like this, since there are some decisions you have to make here on the decoding side about how you want e.g. `{"id":100,"name":"Something Else"}` decoded.

Also for what it's worth you're likely to get an answer more quickly by using either [Gitter](https://gitter.im/circe/circe) or Stack Overflow (or ideally both), since this issue tracker is intended for bug reports and feature requests.

**Comment by terry-dai** [comment]
Instead of using `forProductX`, the other option is: `mapObject(f: JsonObject => JsonObject): Json`
https://github.com/circe/circe/blob/81fc2c97e521b852c8bfb6dc992aae6ce41802e3/modules/core/shared/src/main/scala/io/circe/Json.scala#L89


Use this function to transform the derived generic encoder, i.e. add the missing key value like

```scala
import io.circe.syntax._
import io.circe.Encoder
import io.circe.generic.semiauto.deriveEncoder


implicit val encodeEntityWithBodyParams: Encoder[EntityWithBodyParams] = 
  (e: EntityWithBodyParams) => 
    deriveEncoder[EntityWithBodyParams]
      .apply(e)
      .mapObject(
        jsonObject => jsonObject.add("name", e.name.asJson)
      )

```

**Comment by Mediator7** [comment]
@yadavan88 https://psalm16.github.io/924QAsQxdxl6pq2i0uDCYey2f91jInhkYn8911wCS1IRRDZuk9J/
